//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DMS.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_DMS_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDD_DLG_LOGIN                   129
#define IDD_DLG_DEVCODE                 130
#define IDD_DLG_DEVIN                   131
#define IDD_DLG_VIEWLOG                 132
#define IDD_DLG_INFOIN                  133
#define IDD_DLG_DEVRET                  134
#define IDD_DLG_INFORET                 135
#define IDD_DLG_DEVNEED                 136
#define IDD_DLG_INFONEED                137
#define IDD_DLG_DEV                     138
#define IDD_DLG_DEVALERT                139
#define IDD_DLG_INFOOUT                 140
#define IDD_DLG_DEVOUT                  141
#define IDD_DLG_REPORT                  142
#define IDD_DLG_INFOPRT                 143
#define IDC_EDIT_USRNAME                1000
#define IDC_EDIT_USRPWD                 1001
#define IDC_BTN_DEVCODE                 1002
#define IDC_BTN_DEVIN                   1003
#define IDC_BTN_DEVOUT                  1004
#define IDC_BTN_DEVRET                  1005
#define IDC_BTN_NEED                    1006
#define IDC_BTN_VIEWLOG                 1007
#define IDC_BTN_INFOIN                  1008
#define IDC_BTN_INFOOUT                 1009
#define IDC_BTN_INFORET                 1010
#define IDC_BTN_INFODEV                 1012
#define IDC_BTN_INFONEED                1013
#define IDC_BTN_DEVALERT                1014
#define IDC_BTN_BUYDEV                  1015
#define IDC_EDIT_DCCODE                 1017
#define IDC_EDIT_DCNAME                 1018
#define IDC_BTN_DCADD                   1019
#define IDC_BTN_DCUPD                   1020
#define IDC_BTN_DCDEL                   1021
#define IDC_LIST_DEVCODE                1022
#define IDC_COMBO_DIDEVS                1023
#define IDC_DATETIMEPICKER_DIDATE       1025
#define IDC_EDIT_DIPROVIDER             1027
#define IDC_EDIT_DITEL                  1028
#define IDC_EDIT_DINUMBER               1029
#define IDC_EDIT_DIPRICE                1030
#define IDC_EDIT_DIBUYER                1031
#define IDC_BTN_DIADD                   1032
#define IDC_EDIT_VLDATE                 1034
#define IDC_LIST_VLLOG                  1036
#define IDC_EDIT_VLOPR                  1037
#define IDC_EDIT_VLOP                   1038
#define IDC_BTN_VLRMALL                 1039
#define IDC_LIST_VIEWDEVIN              1040
#define IDC_EDIT_VIDATE                 1041
#define IDC_EDIT_VICODE                 1042
#define IDC_EDIT_VIBUYER                1043
#define IDC_EDIT_VIPRICE                1044
#define IDC_EDIT_VINUMBER               1045
#define IDC_EDIT_VITEL                  1046
#define IDC_EDIT_VIPROVIDER             1047
#define IDC_BTN_VIUPDATE                1048
#define IDC_BTN_VIDEL                   1049
#define IDC_DATETIMEPICKER_DITIME       1050
#define IDC_BTN_DRADD                   1051
#define IDC_COMBO_DRDEVS                1052
#define IDC_DATETIMEPICKER_DRDATE       1053
#define IDC_DATETIMEPICKER_DRTIME       1054
#define IDC_EDIT_DRKEEPER               1055
#define IDC_EDIT_DRNUMBER               1056
#define IDC_EDIT_DRRETER                1057
#define IDC_EDIT_VRCODE                 1058
#define IDC_EDIT_VRDATE                 1059
#define IDC_BTN_VRUPDT                  1060
#define IDC_LIST_VR                     1061
#define IDC_EDIT_VRKEEPER               1062
#define IDC_EDIT_VRNUMBER               1063
#define IDC_EDIT_VRRETER                1064
#define IDC_BTN_VRDEL                   1065
#define IDC_COMBO_DNCODE                1066
#define IDC_EDIT_DNDEPT                 1067
#define IDC_DATETIMEPICKER_DNSTART      1068
#define IDC_DATETIMEPICKER_DNEND        1069
#define IDC_EDIT_DNNUMBER               1070
#define IDC_BTN_DNADD                   1071
#define IDC_EDIT_VNCODE                 1073
#define IDC_EDIT_VNSTART                1074
#define IDC_EDIT_VNEND                  1075
#define IDC_BTN_VNDEL                   1076
#define IDC_LIST_VN                     1077
#define IDC_EDIT_VNDEPT                 1078
#define IDC_EDIT_VNNUMBER               1079
#define IDC_LIST_DEV                    1080
#define IDC_EDIT_DEVCUR                 1082
#define IDC_EDIT_DEVMAX                 1083
#define IDC_EDIT_DEVMIN                 1084
#define IDC_EDIT_DEVTOTAL               1085
#define IDC_COMBO_DEVDEV                1086
#define IDC_BTN_DEVADD                  1087
#define IDC_BTN_DEVUPD                  1088
#define IDC_BTN_DEVDEL                  1089
#define IDC_LIST_DL                     1090
#define IDC_BTN_DLOVER                  1091
#define IDC_BTN_DLBELOW                 1092
#define IDC_BTN_DLALL                   1093
#define IDC_LIST_VO                     1094
#define IDC_EDIT_VOCODE                 1095
#define IDC_EDIT_VODEPT                 1096
#define IDC_EDIT_VODATE                 1097
#define IDC_EDIT_VOSTA                  1098
#define IDC_EDIT_VOKEEPER               1099
#define IDC_EDIT_VONUMBER               1100
#define IDC_EDIT_VOTAKER                1101
#define IDC_EDIT_VOUSAGE                1102
#define IDC_BTN_VODEL                   1103
#define IDC_BTN_VOUPD                   1104
#define IDC_EDIT_DODEPT                 1105
#define IDC_EDIT_DOSTATE                1106
#define IDC_EDIT_DOKEEPER               1107
#define IDC_EDIT_DONUMBER               1108
#define IDC_EDIT_DOTAKER                1109
#define IDC_EDIT_DOUSAGE                1110
#define IDC_BTN_DOADD                   1111
#define IDC_COMBO_DODEVS                1112
#define IDC_DATETIMEPICKER_DODATE       1113
#define IDC_DATETIMEPICKER_DOTIME       1114
#define IDC_COMBO_RPDEVS                1115
#define IDC_EDIT_RPNAME                 1116
#define IDC_EDIT_RPMAX                  1117
#define IDC_EDIT_RPTOTAL                1118
#define IDC_EDIT_RPCUR                  1119
#define IDC_EDIT_RPBUY                  1120
#define IDC_EDIT_RPPROVIDER             1121
#define IDC_EDIT_RPPRICE                1122
#define IDC_BTN_PRINT                   1123
#define IDC_DATETIMEPICKER_PRTIME       1125
#define IDC_DATETIMEPICKER_PRDATE       1126
#define IDC_BTN_VIEWPRT                 1127
#define IDC_BTN_VRPDEL                  1128
#define IDC_LIST_VRP                    1129
#define IDC_EDIT_VPRCODE                1130
#define IDC_EDIT_VPRDATE                1131
#define IDC_EDIT_VRPMAX                 1132
#define IDC_EDIT_VRPCUR                 1133
#define IDC_EDIT_VRPTOTAL               1134
#define IDC_EDIT_VRPPROVIDER            1135
#define IDC_EDIT_VRPBUY                 1136
#define IDC_EDIT_VRPPRICE               1137
#define IDC_BTN_ABOUT                   1138
#define IDC_BTN_HELP                    1141
#define IDC_EDIT_DOMAX                  1142
#define IDC_DATETIMEPICKER1             1144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1146
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
